import pandas as pd
import os

# Urls de la página web acomer.pe
urls_a_comer = [
    "https://acomer.pe/arroz-chaufa-regional/",
    "https://acomer.pe/arroz-chaufa-de-pollo/",
    "https://acomer.pe/tallarin-saltado-de-chifa/",
    "https://acomer.pe/chicharron-de-pollo-al-estilo-oriental/",
    "https://acomer.pe/tiradito-maguro-new-style/",
    "https://acomer.pe/chutney-de-mango/",
    "https://acomer.pe/maki-acebichado/",
    "https://acomer.pe/tallarin-saltado-chino-por-felix-loo/",
    "https://acomer.pe/sopa-fuchifu/",
    "https://acomer.pe/kam-lu-wantan/",
    "https://acomer.pe/wantan-frito/",
    "https://acomer.pe/pollo-chijaukay/",
    "https://acomer.pe/champus/",
    "https://acomer.pe/quinua-carretillera/",
    "https://acomer.pe/marcianos-de-chocolate-con-leche/",
    "https://acomer.pe/limonada-frozen/",
    "https://acomer.pe/chicha-morada/",
    "https://acomer.pe/limonada-hulk/",
    "https://acomer.pe/arroz-chaufa-de-pollo/",
    "https://acomer.pe/tallarin-saltado-de-chifa/",
    "https://acomer.pe/chicharron-de-pollo-al-estilo-oriental/",
    "https://acomer.pe/tallarin-saltado-chino-por-felix-loo/",
    "https://acomer.pe/sopa-fuchifu/",
    "https://acomer.pe/chancho-asado-chino-cha-siu/",
    "https://acomer.pe/chaufa-charapa/",
    "https://acomer.pe/ensalada-rusa/",
    "https://acomer.pe/aji-de-gallina-con-quinua/",
    "https://acomer.pe/tallarines-con-atun-a-la-italiana/",
    "https://acomer.pe/ensalada-waldorf/",
    "https://acomer.pe/ensalada-blanca-navidena/",
    "https://acomer.pe/ensalada-de-fideos/",
    "https://acomer.pe/ensalada-tibia-de-quinua/",
    "https://acomer.pe/jugo-surtido-y-especial/",
    "https://acomer.pe/arroz-al-olivar/",
    "https://acomer.pe/arroz-arabe/",
    "https://acomer.pe/ensalada-de-fideos/",
    "https://acomer.pe/pure-de-papa-navideno/",
    "https://acomer.pe/pure-de-camote/",
    "https://acomer.pe/chanchito-enrollado-crocante/",
    "https://acomer.pe/pierna-de-cerdo-navidena/",
    "https://acomer.pe/pechuga-de-pavo-al-horno/",
    "https://acomer.pe/pollo-al-horno-con-pure-de-papas/",
    "https://acomer.pe/pollo-a-la-cordon-bleu-con-salsa-bechamel/",
    "https://acomer.pe/pizza-casera/",
    "https://acomer.pe/costillas-de-cerdo-a-la-bbq/",
    "https://acomer.pe/cebiche-carretillero/",
    "https://acomer.pe/tiradito-maguro-new-style/",
    "https://acomer.pe/lentejas-a-la-nortena/",
    "https://acomer.pe/pavo-relleno-al-horno/",
    "https://acomer.pe/caldo-de-pollo/",
    "https://acomer.pe/sudado-de-pescado-a-la-nortena/",
    "https://acomer.pe/ensalada-cocida-con-pollo/",
    "https://acomer.pe/ensalada-de-atun/",
    "https://acomer.pe/causa-de-atun/",
    "https://acomer.pe/asado-con-pure/",
    "https://acomer.pe/cebiche-clasico/",
    "https://acomer.pe/tiradito-de-pejerrey/",
    "https://acomer.pe/huevos-de-don-mario-al-jugo/",
    "https://acomer.pe/escabeche-de-pescado/",
    "https://acomer.pe/wraps-de-pollo-anticuchero/",
    "https://acomer.pe/ensalada-cesar/",
    "https://acomer.pe/ensalada-de-atun/",
    "https://acomer.pe/vinagreta-de-polleria/",
    "https://acomer.pe/pavo-navideno-peruano/",
    "https://acomer.pe/alitas-de-pollo-horneadas-con-salsa-bbq/",
    "https://acomer.pe/milanesa-de-pollo/",
    "https://acomer.pe/pavo-relleno-al-horno/",
    "https://acomer.pe/pollo-al-horno/",
    "https://acomer.pe/lomito-de-cerdo-al-horno/",
    "https://acomer.pe/lasana-a-la-bolonesa/",
    "https://acomer.pe/tori-no-karaage/",
    "https://acomer.pe/fettuccine-alfredo/",
    "https://acomer.pe/albondigas-en-salsa-de-tomate/",
    "https://acomer.pe/pasta-en-salsa-bolonesa/",
    "https://acomer.pe/queque-de-naranja/",
    "https://acomer.pe/rosquitas-de-manteca-y-anis/",
    "https://acomer.pe/torta-tres-leches/",
    "https://acomer.pe/torta-helada/",
    "https://acomer.pe/alfajores-de-maicena/",
    "https://acomer.pe/pionono-esponjoso/",
    "https://acomer.pe/besos-de-moza/",
    "https://acomer.pe/besos-de-moza/",
    "https://acomer.pe/tallarin-saltado-con-chicharron-de-pollo/",
    "https://acomer.pe/arroz-norteno-con-pescado-frito/",
    "https://acomer.pe/causa-acebichada/",
    "https://acomer.pe/tallarines-a-la-huancaina-con-lomo-saltado/",
    "https://acomer.pe/papa-rellena-de-lomo-saltado/",
    "https://acomer.pe/salsa-de-aji-parrillero/",
    "https://acomer.pe/tequenos-de-lomo-saltado/",
    "https://acomer.pe/arroz-con-chancho/",
    "https://acomer.pe/arroz-a-la-jardinera/",
    "https://acomer.pe/ocopa-arequipena/",
    "https://acomer.pe/pachamanca-a-la-olla/",
    "https://acomer.pe/papa-a-la-huancaina/",
    "https://acomer.pe/guiso-de-quinua/",
    "https://acomer.pe/pepian-de-choclo/",
    "https://acomer.pe/sancochado-limeno/",
    "https://acomer.pe/sopa-seca-chinchana/",
    "https://acomer.pe/seco-de-cabrito-a-la-nortena/",
    "https://acomer.pe/arroz-con-pato-a-la-chiclayana/",
    "https://acomer.pe/pure-perfecto-con-asado-al-vino-tinto/",
    "https://acomer.pe/papa-rellena/",
    "https://acomer.pe/pollo-a-la-olla/",
    "https://acomer.pe/lomo-saltado/",
    "https://acomer.pe/tallarines-rojos/",
    "https://acomer.pe/bistec-a-lo-pobre/",
    "https://acomer.pe/arroz-tapado/",
    "https://acomer.pe/pollo-navideno-sin-horno/",
    "https://acomer.pe/chanchito-enrollado-crocante/",
    "https://acomer.pe/pavo-al-horno-jugoso/",
    "https://acomer.pe/pavo-oriental/",
    "https://acomer.pe/arroz-con-pollo/",
    "https://acomer.pe/pastel-de-manzana-en-sarten/",
    "https://acomer.pe/mazamorra-morada-con-arroz-con-leche/",
    "https://acomer.pe/cinnamon-rolls/",
    "https://acomer.pe/arroz-con-carne/",
    "https://acomer.pe/mostrito/",
    "https://acomer.pe/locro-de-zapallo/",
    "https://acomer.pe/tallarin-saltado-con-carne/",
    "https://acomer.pe/pollo-a-la-coca-cola/",
    "https://acomer.pe/higado-encebollado/",
    "https://acomer.pe/pollo-a-la-mostaza/",
    "https://acomer.pe/sopa-de-garbanzos-con-carne/",
    "https://acomer.pe/sopa-de-pollo/",
    "https://acomer.pe/picante-de-carne/",
    "https://acomer.pe/salchipapa-con-todas-las-cremas/",
    "https://acomer.pe/caldo-de-mote/",
    "https://acomer.pe/cebiche-de-pollo/",
    "https://acomer.pe/arvejas-partidas/",
    "https://acomer.pe/pollo-al-horno-con-pure-de-papas/",
    "https://acomer.pe/aji-de-gallina-con-quinua/",
    "https://acomer.pe/caigua-rellena/",
    "https://acomer.pe/chaufa-de-mariscos/",
    "https://acomer.pe/pollo-a-la-brasa-casero/",
    "https://acomer.pe/ensalada-de-quinua-oriental/",
    "https://acomer.pe/pollo-con-verduras-al-vapor/",
    "https://acomer.pe/chaufa-de-quinua/",
    "https://acomer.pe/ensalada-de-arroz-integral/",
    "https://acomer.pe/cake-de-limon-con/",
    "https://acomer.pe/vainitas-saltadas/",
    "https://acomer.pe/arroz-al-olivar/",
    "https://acomer.pe/chanchito-crocante/",
    "https://acomer.pe/ensalada-blanca-navidena/",
    "https://acomer.pe/arroz-arabe/",
    "https://acomer.pe/lechon-al-horno/",
    "https://acomer.pe/escabeche-de-pollo/",
    "https://acomer.pe/estofado-de-pollo/",
    "https://acomer.pe/pollo-frito-con-ensalada-rusa/",
    "https://acomer.pe/salsa-bolognesa-con-coliflor/",
    "https://acomer.pe/guiso-de-trigo/",
    "https://acomer.pe/sopa-de-semola/",
    "https://acomer.pe/tallarines-verdes/",
    "https://acomer.pe/chupe-de-bonito-con-langostinos/",
    "https://acomer.pe/pure-de-papas-con-espinaca/",
    "https://acomer.pe/chupe-de-bonito-con-langostinos/",
    "https://acomer.pe/ensalada-del-campo/",
    "https://acomer.pe/estofado-de-carne/",
    "https://acomer.pe/sopa-de-moron/",
    "https://acomer.pe/aguadito-de-pollo/",
    "https://acomer.pe/higadito-frito/",
    "https://acomer.pe/lentejas-a-la-nortena/",
    "https://acomer.pe/bistec-encebollado/",
    "https://acomer.pe/cau-cau/",
    "https://acomer.pe/pollo-al-mani/",
    "https://acomer.pe/yuquitas-fritas-caseras/",
    "https://acomer.pe/seco-de-carne-con-frejoles/",
    "https://acomer.pe/chanfainita/",
    "https://acomer.pe/lentejas-guisadas/",
    "https://acomer.pe/pollo-broaster/",
    "https://acomer.pe/pollo-chijaukay/",
    "https://acomer.pe/caldo-de-gallina/",
    "https://acomer.pe/carapulcra/",
    "https://acomer.pe/menestron/",
    "https://acomer.pe/jalea-mixta/",
    "https://acomer.pe/enrollados-de-pejerrey/",
]

print("Cantidad de urls_a_comer: ", len(urls_a_comer))

set_urls_a_comer = list(set(urls_a_comer))
print("Cantidad de urls únicos: ", len(set_urls_a_comer))

# Crear un DataFrame con las urls únicas
print("Dataframe creado...")
df_urls_a_comer = pd.DataFrame(set_urls_a_comer, columns=["urls"])

try:
    print("Dataframe guardando ...")
    df_urls_a_comer.to_csv("../data/urls_a_comer.csv", index=False)
    print("Dataframe guardado con éxito en ../data/urls_a_comer.csv ")
except Exception as e:
    print("Error al guardar el dataframe: ", e)
    print("Dataframe no guardado ...")
